### ISSUE TITLE
Breaking change at Handler modularization

### ISSUE THREAD

**Issue by johnpyp** [RealBlazeIt/patron.js#13]
A  breaking change was introduced here: https://github.com/vim2meta/patron.js/commit/0c7134f24b8542ac4de6ce0dd9c1df0fc8004c13

Here is the error when using this commit version, and no errors are produced from the previous commit.

```
johnpyp@johnpyp-UX330UAK:~/Desktop/Coding/dice-nation$ node src/index
/home/johnpyp/Desktop/Coding/dice-nation/node_modules/patron.js/src/structures/Handler.js:322
      throw new TypeError('Handler.registry must be an instance of the registry.');
      ^

TypeError: Handler.registry must be an instance of the registry.
    at Function.validateHandler (/home/johnpyp/Desktop/Coding/dice-nation/node_modules/patron.js/src/structures/Handler.js:322:13)
    at new Handler (/home/johnpyp/Desktop/Coding/dice-nation/node_modules/patron.js/src/structures/Handler.js:25:22)
    at Object.<anonymous> (/home/johnpyp/Desktop/Coding/dice-nation/src/events/message.js:10:17)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

**Comment by LJNeon** [comment]
yes the current github is the work in progress of v3, there have already been breaking changes made and there may be even more. The Handler now requires an options object.

**Comment by LJNeon** [comment]
If you want to avoid any breaking changes until v3 is fully released I'd recommend installing the npm package instead of the github one.

**Comment by LJNeon** [comment]
The docs should be updated with any breaking changes however, so it shouldn't be too hard to update your code.
